server.port=8080
server.error.include-stacktrace=always

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/renteasedb
spring.datasource.username=rentease_user
spring.datasource.password=rentease_password
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Create or update schema automatically
spring.jpa.hibernate.ddl-auto=update

# Email / SMTP Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tahmidislamsamin@gmail.com
spring.mail.password=gtrlcvrafsquloju
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


# Allow large Base64 Image Uploads
server.tomcat.max-http-form-post-size=20MB
