version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: rentease_db
    environment:
      POSTGRES_USER: rentease_user
      POSTGRES_PASSWORD: rentease_password
      POSTGRES_DB: renteasedb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
