/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Category = IDL.Variant({
  'shifting_service' : IDL.Null,
  'hotel' : IDL.Null,
  'house' : IDL.Null,
  'flat' : IDL.Null,
  'convention_hall' : IDL.Null,
});
export const BrowseFilter = IDL.Record({
  'locationQuery' : IDL.Opt(IDL.Text),
  'category' : IDL.Opt(Category),
});
export const ListingId = IDL.Nat;
export const UserId = IDL.Principal;
export const Timestamp = IDL.Int;
export const ListingPublic = IDL.Record({
  'id' : ListingId,
  'imageKeys' : IDL.Vec(IDL.Text),
  'owner' : UserId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'category' : Category,
  'location' : IDL.Text,
  'contactPhone' : IDL.Text,
});
export const CreateListingInput = IDL.Record({
  'imageKeys' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'description' : IDL.Text,
  'category' : Category,
  'location' : IDL.Text,
  'contactPhone' : IDL.Text,
});
export const UserProfilePublic = IDL.Record({
  'id' : UserId,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const UpdateListingInput = IDL.Record({
  'imageKeys' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'description' : IDL.Text,
  'location' : IDL.Text,
  'contactPhone' : IDL.Text,
});
export const UpsertProfileInput = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  'browseListings' : IDL.Func(
      [BrowseFilter],
      [IDL.Vec(ListingPublic)],
      ['query'],
    ),
  'createListing' : IDL.Func([CreateListingInput], [ListingPublic], []),
  'deleteListing' : IDL.Func([ListingId], [IDL.Bool], []),
  'getListing' : IDL.Func([ListingId], [IDL.Opt(ListingPublic)], ['query']),
  'getMyListings' : IDL.Func([], [IDL.Vec(ListingPublic)], ['query']),
  'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfilePublic)], []),
  'updateListing' : IDL.Func(
      [ListingId, UpdateListingInput],
      [IDL.Opt(ListingPublic)],
      [],
    ),
  'upsertMyProfile' : IDL.Func([UpsertProfileInput], [UserProfilePublic], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Category = IDL.Variant({
    'shifting_service' : IDL.Null,
    'hotel' : IDL.Null,
    'house' : IDL.Null,
    'flat' : IDL.Null,
    'convention_hall' : IDL.Null,
  });
  const BrowseFilter = IDL.Record({
    'locationQuery' : IDL.Opt(IDL.Text),
    'category' : IDL.Opt(Category),
  });
  const ListingId = IDL.Nat;
  const UserId = IDL.Principal;
  const Timestamp = IDL.Int;
  const ListingPublic = IDL.Record({
    'id' : ListingId,
    'imageKeys' : IDL.Vec(IDL.Text),
    'owner' : UserId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'category' : Category,
    'location' : IDL.Text,
    'contactPhone' : IDL.Text,
  });
  const CreateListingInput = IDL.Record({
    'imageKeys' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'description' : IDL.Text,
    'category' : Category,
    'location' : IDL.Text,
    'contactPhone' : IDL.Text,
  });
  const UserProfilePublic = IDL.Record({
    'id' : UserId,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const UpdateListingInput = IDL.Record({
    'imageKeys' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'description' : IDL.Text,
    'location' : IDL.Text,
    'contactPhone' : IDL.Text,
  });
  const UpsertProfileInput = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    'browseListings' : IDL.Func(
        [BrowseFilter],
        [IDL.Vec(ListingPublic)],
        ['query'],
      ),
    'createListing' : IDL.Func([CreateListingInput], [ListingPublic], []),
    'deleteListing' : IDL.Func([ListingId], [IDL.Bool], []),
    'getListing' : IDL.Func([ListingId], [IDL.Opt(ListingPublic)], ['query']),
    'getMyListings' : IDL.Func([], [IDL.Vec(ListingPublic)], ['query']),
    'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfilePublic)], []),
    'updateListing' : IDL.Func(
        [ListingId, UpdateListingInput],
        [IDL.Opt(ListingPublic)],
        [],
      ),
    'upsertMyProfile' : IDL.Func([UpsertProfileInput], [UserProfilePublic], []),
  });
};

export const init = ({ IDL }) => { return []; };