/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface UpsertProfileInput {
    name: string;
    email: string;
    address: string;
    phone: string;
}
export type UserId = Principal;
export type Timestamp = bigint;
export interface ListingPublic {
    id: ListingId;
    imageKeys: Array<string>;
    owner: UserId;
    name: string;
    createdAt: Timestamp;
    description: string;
    category: Category;
    location: string;
    contactPhone: string;
}
export type ListingId = bigint;
export interface CreateListingInput {
    imageKeys: Array<string>;
    name: string;
    description: string;
    category: Category;
    location: string;
    contactPhone: string;
}
export interface BrowseFilter {
    locationQuery?: string;
    category?: Category;
}
export interface UserProfilePublic {
    id: UserId;
    name: string;
    email: string;
    address: string;
    phone: string;
}
export interface UpdateListingInput {
    imageKeys: Array<string>;
    name: string;
    description: string;
    location: string;
    contactPhone: string;
}
export enum Category {
    shifting_service = "shifting_service",
    hotel = "hotel",
    house = "house",
    flat = "flat",
    convention_hall = "convention_hall"
}
export interface backendInterface {
    browseListings(filter: BrowseFilter): Promise<Array<ListingPublic>>;
    createListing(input: CreateListingInput): Promise<ListingPublic>;
    deleteListing(id: ListingId): Promise<boolean>;
    getListing(id: ListingId): Promise<ListingPublic | null>;
    getMyListings(): Promise<Array<ListingPublic>>;
    getMyProfile(): Promise<UserProfilePublic | null>;
    updateListing(id: ListingId, input: UpdateListingInput): Promise<ListingPublic | null>;
    upsertMyProfile(input: UpsertProfileInput): Promise<UserProfilePublic>;
}
import type { BrowseFilter as _BrowseFilter, Category as _Category, CreateListingInput as _CreateListingInput, ListingId as _ListingId, ListingPublic as _ListingPublic, Timestamp as _Timestamp, UserId as _UserId, UserProfilePublic as _UserProfilePublic } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async browseListings(arg0: BrowseFilter): Promise<Array<ListingPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.browseListings(to_candid_BrowseFilter_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.browseListings(to_candid_BrowseFilter_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async createListing(arg0: CreateListingInput): Promise<ListingPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.createListing(to_candid_CreateListingInput_n10(this._uploadFile, this._downloadFile, arg0));
                return from_candid_ListingPublic_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createListing(to_candid_CreateListingInput_n10(this._uploadFile, this._downloadFile, arg0));
            return from_candid_ListingPublic_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteListing(arg0: ListingId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteListing(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteListing(arg0);
            return result;
        }
    }
    async getListing(arg0: ListingId): Promise<ListingPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getListing(arg0);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getListing(arg0);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyListings(): Promise<Array<ListingPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyListings();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyListings();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyProfile(): Promise<UserProfilePublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile();
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile();
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateListing(arg0: ListingId, arg1: UpdateListingInput): Promise<ListingPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateListing(arg0, arg1);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateListing(arg0, arg1);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async upsertMyProfile(arg0: UpsertProfileInput): Promise<UserProfilePublic> {
        if (this.processError) {
            try {
                const result = await this.actor.upsertMyProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.upsertMyProfile(arg0);
            return result;
        }
    }
}
function from_candid_Category_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_ListingPublic_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ListingPublic): ListingPublic {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ListingPublic]): ListingPublic | null {
    return value.length === 0 ? null : from_candid_ListingPublic_n6(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfilePublic]): UserProfilePublic | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ListingId;
    imageKeys: Array<string>;
    owner: _UserId;
    name: string;
    createdAt: _Timestamp;
    description: string;
    category: _Category;
    location: string;
    contactPhone: string;
}): {
    id: ListingId;
    imageKeys: Array<string>;
    owner: UserId;
    name: string;
    createdAt: Timestamp;
    description: string;
    category: Category;
    location: string;
    contactPhone: string;
} {
    return {
        id: value.id,
        imageKeys: value.imageKeys,
        owner: value.owner,
        name: value.name,
        createdAt: value.createdAt,
        description: value.description,
        category: from_candid_Category_n8(_uploadFile, _downloadFile, value.category),
        location: value.location,
        contactPhone: value.contactPhone
    };
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    shifting_service: null;
} | {
    hotel: null;
} | {
    house: null;
} | {
    flat: null;
} | {
    convention_hall: null;
}): Category {
    return "shifting_service" in value ? Category.shifting_service : "hotel" in value ? Category.hotel : "house" in value ? Category.house : "flat" in value ? Category.flat : "convention_hall" in value ? Category.convention_hall : value;
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ListingPublic>): Array<ListingPublic> {
    return value.map((x)=>from_candid_ListingPublic_n6(_uploadFile, _downloadFile, x));
}
function to_candid_BrowseFilter_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BrowseFilter): _BrowseFilter {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_Category_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): _Category {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_CreateListingInput_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateListingInput): _CreateListingInput {
    return to_candid_record_n11(_uploadFile, _downloadFile, value);
}
function to_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    imageKeys: Array<string>;
    name: string;
    description: string;
    category: Category;
    location: string;
    contactPhone: string;
}): {
    imageKeys: Array<string>;
    name: string;
    description: string;
    category: _Category;
    location: string;
    contactPhone: string;
} {
    return {
        imageKeys: value.imageKeys,
        name: value.name,
        description: value.description,
        category: to_candid_Category_n3(_uploadFile, _downloadFile, value.category),
        location: value.location,
        contactPhone: value.contactPhone
    };
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    locationQuery?: string;
    category?: Category;
}): {
    locationQuery: [] | [string];
    category: [] | [_Category];
} {
    return {
        locationQuery: value.locationQuery ? candid_some(value.locationQuery) : candid_none(),
        category: value.category ? candid_some(to_candid_Category_n3(_uploadFile, _downloadFile, value.category)) : candid_none()
    };
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): {
    shifting_service: null;
} | {
    hotel: null;
} | {
    house: null;
} | {
    flat: null;
} | {
    convention_hall: null;
} {
    return value == Category.shifting_service ? {
        shifting_service: null
    } : value == Category.hotel ? {
        hotel: null
    } : value == Category.house ? {
        house: null
    } : value == Category.flat ? {
        flat: null
    } : value == Category.convention_hall ? {
        convention_hall: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
