/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BrowseFilter {
  'locationQuery' : [] | [string],
  'category' : [] | [Category],
}
export type Category = { 'shifting_service' : null } |
  { 'hotel' : null } |
  { 'house' : null } |
  { 'flat' : null } |
  { 'convention_hall' : null };
export interface CreateListingInput {
  'imageKeys' : Array<string>,
  'name' : string,
  'description' : string,
  'category' : Category,
  'location' : string,
  'contactPhone' : string,
}
export type ListingId = bigint;
export interface ListingPublic {
  'id' : ListingId,
  'imageKeys' : Array<string>,
  'owner' : UserId,
  'name' : string,
  'createdAt' : Timestamp,
  'description' : string,
  'category' : Category,
  'location' : string,
  'contactPhone' : string,
}
export type Timestamp = bigint;
export interface UpdateListingInput {
  'imageKeys' : Array<string>,
  'name' : string,
  'description' : string,
  'location' : string,
  'contactPhone' : string,
}
export interface UpsertProfileInput {
  'name' : string,
  'email' : string,
  'address' : string,
  'phone' : string,
}
export type UserId = Principal;
export interface UserProfilePublic {
  'id' : UserId,
  'name' : string,
  'email' : string,
  'address' : string,
  'phone' : string,
}
export interface _SERVICE {
  'browseListings' : ActorMethod<[BrowseFilter], Array<ListingPublic>>,
  'createListing' : ActorMethod<[CreateListingInput], ListingPublic>,
  'deleteListing' : ActorMethod<[ListingId], boolean>,
  'getListing' : ActorMethod<[ListingId], [] | [ListingPublic]>,
  'getMyListings' : ActorMethod<[], Array<ListingPublic>>,
  'getMyProfile' : ActorMethod<[], [] | [UserProfilePublic]>,
  'updateListing' : ActorMethod<
    [ListingId, UpdateListingInput],
    [] | [ListingPublic]
  >,
  'upsertMyProfile' : ActorMethod<[UpsertProfileInput], UserProfilePublic>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];